### ISSUE TITLE
failed to build

### ISSUE THREAD

**Issue by keitti73** [turtton/dotnix#2]
![Screenshot from 2024-11-14 10-22-18](https://github.com/user-attachments/assets/4377cb49-eb97-46c8-90b0-7c9479e1c250)
 The build will fail.

How do I edit configuraion.nix?
[configuration.zip](https://github.com/user-attachments/files/17741338/configuration.zip)

# System Details Report
---

## Report details
- **Date generated:**                              2024-11-14 10:33:56

## Hardware Information:
- **Hardware Model:**                              AZW Speed S
- **Memory:**                                      8.0 GiB
- **Processor:**                                   Intel® Core™ i5-8279U × 8
- **Graphics:**                                    Intel® Iris® Plus Graphics 655 (CFL GT3)
- **Disk Capacity:**                               256.1 GB

## Software Information:
- **Firmware Version:**                            CB1D_FV106
- **OS Name:**                                     NixOS 24.05 (Uakari)
- **OS Build:**                                    24.05.6043.64b80bfb316b
- **OS Type:**                                     64 ビット
- **GNOME Version:**                               46
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.6.58

**Comment by turtton** [comment]
Fixed in 934dc63942284674f2946817689baea7e05e29ca

Btw, `maindesk` profile installs many applications(Over 100GB). I recommend to try `virtbox` profile(make sure [hardware-configuration.nix](https://github.com/turtton/dotnix/blob/main/hosts/virtbox/hardware-configuration.nix) is replaced your `/etc/nixos/hardware-configuration.nix` )
